### ISSUE TITLE
path设置路径的真实含义

### ISSUE THREAD

**Issue by zeroone2005** [kkokk/poster#11]
$poster->path($path); # 设置路径

这是设置保存路径呢还是是什么，保存文件名怎么设置 ，的实例是 poster/poster_user 这里理解为poster_user目录呢还是 poster_user.xxx图片

**Comment by kkokk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkokk** [comment]
路径如果有斜杠，斜杠最右为文件名，前面都是目录路径不存在会创建，如果没有斜杠就直接是文件名。poster/poster_user含义poster为目录名poster_user为文件名、不指定后缀默认是png；
