### ISSUE TITLE
多海报循环生成时，会返回同一个地址

### ISSUE THREAD

**Issue by plamYuan** [kkokk/poster#12]
感谢分享
多个海报循环生成时，会返回相同的海报地址，而且对应海报文件夹只有一张海报

foreach ($templateList as $v){
 $fileName = time().rand(100,999).'.jpg';
  try {
  $posterManager = new PosterManager('poster/'. $fileName);
  $res = $posterManager->buildImDst($v['template_url'], $v['width'], $v['height'], [255,255,255,1], false)
      ->buildImage($pageScene['qrcode_url'],550,$topBannerHeight+20,0,0,160,160,false,'circle')
      ->getPoster();
  }catch (Exception $e){
      Log::error('生成海报失败02');
  }
  dump($res);
}

输出结果
array(1) {
  ["url"] => string(24) "poster/1675755107906.jpg"
}
array(1) {
  ["url"] => string(24) "poster/1675755107906.jpg"
}
array(1) {
  ["url"] => string(24) "poster/1675755107906.jpg"
}

**Comment by kkokk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkokk** [comment]
你好，感谢你的提问，循环的时候使用$poster->path($path); # 设置路径
