### ISSUE TITLE
升级之后莫名其妙的居中的都不居中了

### ISSUE THREAD

**Issue by indiboy** [kkokk/poster#13]
代码还没有看，先来反馈一下。

**Comment by kkokk** [comment]
贴一下代码看看😂

**Comment by indiboy** [comment]
原来好好的，升级之后不可以了，代码应该没问题。
`$buildTextArr[] = [
            'content' => $smalltext,
            'dst_x' => 'center',
            'dst_y' => 760,
            'font' => 40,
            'rgba' => [51, 51, 51, 1],
            'max_w' => 0,
            'font_family' => $source_path . 'data/fonts/Alibaba-PuHuiTi-Light.ttf',
            'weight' => 1,
            'space' => 20
        ];`

**Comment by indiboy** [comment]
看了下生成图片的效果，应该是文字起点变成中间了。

**Comment by kkokk** [comment]
是的，我修改一下

**Comment by kkokk** [comment]
可以了，再更新一下
