### ISSUE TITLE
使用imagick扩展，用buildImage方法时，type设置circle无效

### ISSUE THREAD

**Issue by wang-junda** [kkokk/poster#15]
使用gd扩展就ok，能正常圆角，但imagick扩展时就不行，无效

**Comment by kkokk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkokk** [comment]
谢谢指出，已修复
