### ISSUE TITLE
使用getPoster时会有路径的问题

### ISSUE THREAD

**Issue by xihuantudi** [kkokk/poster#16]
使用getPoster时如果加了参数，比如getPoster('test')，这个参数应该是单纯作为文件名的形式拼接到输出路径中，但是加入了这个参数后,GDTrait文件中的returnImage函数最后输出就会带上原本包的路径并拼接在配置的路径前面，举个例子：

**Comment by xihuantudi** [comment]
我加参数前的路径是：/home/www/monda-read/read-api/runtime/poster/.png，但是在加了之后就变成了/home/www/monda-read/read-api/vendor/kkokk/poster/src/Image/Drivers/../../../tests//home/www/monda-read/read-api/runtime/poster/test.png，且getPoster参数的输出里是没有这个项目路径只会输出/home/www/monda-read/read-api/runtime/poster/test.png的

**Comment by kkokk** [comment]
getPoster需要传完整路径，而不是文件名

**Comment by kkokk** [comment]
如果是fpm形式访问可以传递基于项目根目录的相对路径，cli要传绝对路径，例如：/home/www/monda-read/read-api/runtime/poster/test.png

**Comment by kkokk** [comment]
文件会以传递参数的test.png作为文件名
