### ISSUE TITLE
请问文字合成支持html跟css吗

### ISSUE THREAD

**Issue by MaximilianYeung** [kkokk/poster#2]
合成文字时有些文字需要重点强调 需要改变颜色或字体 请问如何操作 感谢

**Comment by kkokk** [comment]
不好意思，还不支持html和css，但是可以改变文字颜色和大小

**Comment by kkokk** [comment]
> 合成文字时有些文字需要重点突出需要改变颜色或字体请问如何操作感谢
不好意思，还不支持html和css，但是可以改变文字颜色和大小

**Comment by kkokk** [comment]
@MaximilianYeung 字体也可改变
