### ISSUE TITLE
运行tests后二维码未被添加

### ISSUE THREAD

**Issue by worker1024** [kkokk/poster#3]
如题：运行tests后二维码未被添加！其他正常。
合成速度受什么影响，感觉加载很慢，能否优化

**Comment by kkokk** [comment]
> 如题：运行tests后二维码未被添加！其他正常。
> 合成速度受什么影响，感觉加载很慢，能否优化

合成速度受图片大小影响，二维码参数变了，你看文档调一下
![image](https://user-images.githubusercontent.com/18664878/103413063-fe70cf80-4bb2-11eb-8e08-49e5e9d17d08.png)

**Comment by kkokk** [comment]
因为最近挺忙的，暂时没时间优化

**Comment by kkokk** [comment]
> 如题：运行测试后二维码可以添加！其他正常。
> 合成速度受什么影响，感觉加载很慢，能否优化

因为最近挺忙的，暂时没时间优化

**Comment by worker1024** [comment]
好的，辛苦了，感觉二维码宽高直接定义一个参数就好了，常规二维码均为正方形

**Comment by kkokk** [comment]
> 好的，辛苦了，感觉二维码宽高直接定义一个参数就好了，常规二维码均为正方形

我这边考虑的是单独控制，你可以自己修改下
