### ISSUE TITLE
望支持gif添加文字与图片

### ISSUE THREAD

**Issue by worker1024** [kkokk/poster#4]
望支持gif添加文字与图片，合成速度较慢 提高服务器配置速度改变不明显

**Comment by kkokk** [comment]
> 望支持gif添加文字与图片，合成速度较慢提高服务器配置速度改变不明显
后续会考虑增加该功能，合成速度跟图片大小有关，图片过大，合成就会相对较慢

**Comment by kkokk** [comment]
使用imagick方式添加支持了
