### ISSUE TITLE
插入图片希望可以设置图片角度，那样就可以呈现出意想不到的效果

### ISSUE THREAD

**Issue by worker1024** [kkokk/poster#6]

**Comment by kkokk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkokk** [comment]
> _No description provided._
后续考虑加入该功能

**Comment by jecoy** [comment]
需要这个功能

**Comment by kkokk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkokk** [comment]
安排

**Comment by kkokk** [comment]
已安排
