### ISSUE TITLE
合成文字

### ISSUE THREAD

**Issue by yanyaobo** [kkokk/poster#7]
合成文字的时候，设置了最大换行宽度，又设置了字体间距，好像计算换行的时候，没有考虑字体间距，是这样吗？

**Comment by kkokk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkokk** [comment]
是的，没有计算间距，谢谢你的提醒
