### ISSUE TITLE
能否改进一下（背景/遮罩），分开，遮罩可以这是大小，位置，颜色，透明度

### ISSUE THREAD

**Issue by indiboy** [kkokk/poster#9]
谢谢

**Comment by kkokk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkokk** [comment]
可以的

**Comment by indiboy** [comment]
非常感谢，现在这个太简单了，直接全部遮罩了，可操作余地太低了。
还建议多增加几个图形，或者可以自定义图形。
遮罩如果可以颜色 渐变就更好了。

**Comment by kkokk** [comment]
已添加，看文档更新内容
